### ISSUE TITLE
Issue with arguments in "create_stream"

### ISSUE THREAD

**Issue by josecso** [qweeze/rstream#119]
Hi, when creating a Stream in RabbitMQ v.3.11 through the procedure below we notice that the Stream is in fact created, however, none of the arguments are used. Please let me know if this is the correct way to pass in arguments to the "create_stream" function.

```
async def main():
    async with Producer("hostname", username="", password="") as producer:
        args={'x-max-age':'2D', 'x-max-length-bytes':1024}
        # create a stream if it doesn't already exist
        await producer.create_stream(STREAM, args, exists_ok=True)
```
thanks in advance for you help and attention
José

**Comment by Gsantomaggio** [comment]
Hi @josecso 

```python
 args = {'max-age': '2D', 'max-length-bytes': 1024}
 await producer.create_stream(STREAM, args, exists_ok=True)
```

Without `x-`

**Comment by josecso** [comment]
Perfect. It worked! thanks for the quick reply!
