### ISSUE TITLE
Support matching confirmation messages in asynchronous sending mode

### ISSUE THREAD

**Issue by garvenlee** [qweeze/rstream#122]
![7e6540b2bf8c4078f08dade155eec94d](https://github.com/qweeze/rstream/assets/38970560/72520a71-7364-4fd8-a1b9-38474a7a094e)

In callback `on_publish_confirm`, the message_id needs to be converted into a message tag at the application layer, which requires a mapping object, but the `send` method provided in `rstream.SuperStreamProducer` just sends out the message asynchronously and only provides an confirmation callback. My approach is to change the hash routing function in python runtime, but I think it’s weird in this way. But If the `send` method can return a `Future` or provide a message map internally, it will be awesome

**Comment by Gsantomaggio** [comment]
Could you please copy the issue's code instead of the image? 

With the  [markdown code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks)  

Thank you

**Comment by garvenlee** [comment]
Here is a simple wrapper for SuperStreamProducer

```Python
class RMQService(AsyncContextManager):
    def __init__(
        self,
        setting: ServerSetting,
    ) -> None:
        self.setting = setting

        self._backend: RMQStreamBackend
        self._producer: SuperStreamProducer
        self.ack_queue: Queue

    async def initialize_publisher(self, producer: Producer, metadata: Metadata):
        partitions = await metadata.partitions()

        sequence_recorder = {}
        for partition in partitions:
            publisher = await producer._get_or_create_publisher(partition)
            sequence_recorder[partition] = int(str(publisher.sequence._seq)[6:-1])

        self.sequence_recorder = sequence_recorder

        HashRoutingMurmurStrategy.route = self.route
        self.partition_cache = LRUCache(maxsize=2**14)
        self.send_waiters: dict[int, Message] = dict()

    async def route(self, message: GrpcMessageWrapper, metadata: Metadata) -> list[str]:
        streams = []

        uuid = message.data.uid
        cache = self.partition_cache
        if (stream := cache.get(uuid)) is None:
            key_bytes = bytes(uuid, "UTF-16")
            hash = mmh3.hash_bytes(key_bytes, 104729)

            partitions = await metadata.partitions()
            route = int.from_bytes(hash, "little", signed=False) % len(partitions)
            stream = partitions[route]
            cache[uuid] = stream

        self.send_waiters[self.sequence_recorder[stream]] = message.data
        self.sequence_recorder[stream] += 1
        streams.append(stream)
        return streams

    def publish_confirm_cb(self, confirmation: ConfirmationStatus):
        if confirmation.is_confirmed:
            message = self.send_waiters[confirmation.message_id]
            self.ack_queue.put_nowait(message)
        else:
            resp_code = confirmation.response_code
            # wait user to find timeout
            logger.warning(f"Failed to Push: {resp_code}")

    async def publish_message(self, message: Message):
        await self._producer_send(GrpcMessageWrapper(message))

    async def __aenter__(self):
        self._loop = get_running_loop()

        setting = self.setting
        self._backend = backend = RMQStreamBackend(
            host=setting.RMQ_HOST,
            port=setting.RMQ_PORT,
            username=setting.RMQ_USERNAME,
            password=setting.RMQ_PASSWORD,
        )

        super_stream_producer: SuperStreamProducer = await backend.create_producer(
            super_name=setting.RMQ_STREAM_NAME,
            routing_extractor=None,
            default_batch_publishing_delay=0.1,
        )
        self._producer_send = partial(
            super_stream_producer.send, on_publish_confirm=self.publish_confirm_cb
        )

        await self.initialize_publisher(
            super_stream_producer._producer, super_stream_producer.super_stream_metadata
        )
        return self

    async def __aexit__(self, exc_tp, exc_val, exc_tb):
        await self._backend.close(exc_tp, exc_val, exc_tb)


```

**Comment by Gsantomaggio** [comment]
The client does not support this feature at the moment. 
Mapping sent messages with received messages is out of protocol scope. 

The [.NET client](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client) and [Java client](https://github.com/rabbitmq/rabbitmq-stream-java-client)  have the mapping messages with timeout etc .....

We should consider adding this feature. 
The idea could be to extend the `Producer` class with the mapping., a pseudo-code:

```python
RProducer = class(Producer)

mapping = dict<id,message>

def send(message)
    mapping.add(id, message)
    base.send(message)

on_confirm(id)
    mapping.removeById(id)

```

We want to avoid to touch the `Producer`.  Same for the `SuperStream`

**Comment by garvenlee** [comment]
Maybe producer.send returns a Future like aiokafka? And I see MessageAccumulater in Java client as you mentioned above, Is it a performance problem?

**Comment by garvenlee** [comment]
Not yet. I use rstream to store chat messages sent by users in RabbitMQ, which is said to get more throughput than normal queues, but I need to look for a confirmation mechanism that looks pythonic

**Comment by garvenlee** [comment]
It doesn’t matter, this is Python. In this way, my server uses multiprocess，but in a multi-process program, there is a SuperStreamProducer in each process, I found there may be serveral publishers of the same publisher_name in different processes, which call query_publish_sequence to get the same value before publishing the message? Then increment the publishing_id independently, whether there is a possibility of message loss in such a scenario

**Comment by DanielePalaia** [comment]
Hi @garvenlee thanks for the feedback on this. The functionality seems interesting but at the moment is not on our priority as this is out of scope from the protocol itself and we don't want to modify the library. Maybe it is something we can think of in the future in case we will decide to add a "smart layer" similarly on how the Java and .NET clients are now doing.
