### ISSUE TITLE
Memory Leak in Client

### ISSUE THREAD

**Issue by garvenlee** [qweeze/rstream#125]
The implementation of Client.waiters is a `defaultdict(set)`, each waiter will only be poped out from the `set` when it completes, while the underlying set will still occupy memory. Similarly, within the `_listener` task, after a frame is read, `defaultdict` creates a `set` internally when calling `waiters[key]` with the key not in waiters,  which is useless but has not been cleaned up.

**Comment by garvenlee** [comment]
And why needs a set factory in defaultdict?

**Comment by qweeze** [comment]
Thanks @garvenlee! Yep, that's a bug. Submitted a fix #129
