### ISSUE TITLE
Make Handler in Client._listener a Task

### ISSUE THREAD

**Issue by garvenlee** [qweeze/rstream#126]
Now, rstream treats each frame’s handler as a coroutine, if this coro blocks or takes a long time, the entire listener task will be blocked, which will decrease the rate of message consumption.

**Comment by DanielePalaia** [comment]
Hi @qweeze I would like to double check with you about this. Do you see any issue if we implement this modification on the client module? I think the issue is referring to line 209 of the client class when we call handler(frame)

**Comment by garvenlee** [comment]
wrapper the `handler(frame)` with `asyncio.create_task` may be fine.

**Comment by DanielePalaia** [comment]
I'm doing a few tests I think it should be fine.

This issue is also linked to: https://github.com/qweeze/rstream/issues/80 and https://github.com/qweeze/rstream/issues/123

So I guess that when we implement it also https://github.com/qweeze/rstream/issues/123 should be fine

**Comment by qweeze** [comment]
Hi @garvenlee 
Yes, it seems to be the case currently that if user provide a long-running callback to `Consumer.subscribe`, listener would block.
I'm not sure if we should just spawn Tasks on each handler though, it might be unsafe to create an uncontrolled number of tasks. Perhaps we should limit concurrency with `asyncio.Queue` / `asyncio.Semaphore`

> I think the issue is referring to line 209 of the client class when we call handler(frame)

If I understood it right the issue is [this line](https://github.com/qweeze/rstream/blob/master/rstream/client.py#L211)

**Comment by qweeze** [comment]
This change would also affect how `Credit` frames are sent. I think we should at least run a benchmark first

**Comment by garvenlee** [comment]
> Hi @garvenlee Yes, it seems to be the case currently that if user provide a long-running callback to `Consumer.subscribe`, listener would block. I'm not sure if we should just spawn Tasks on each handler though, it might be unsafe to create an uncontrolled number of tasks. Perhaps we should limit concurrency with `asyncio.Queue` / `asyncio.Semaphore`
> 
> > I think the issue is referring to line 209 of the client class when we call handler(frame)
> 
> If I understood it right the issue is [this line](https://github.com/qweeze/rstream/blob/master/rstream/client.py#L211)

Yes, it seems to require back pressure and a limit on the number of tasks. I see `aiormq` just directly `create_task` with `basic_qos`, so `rstream` maybe do the same?

**Comment by qweeze** [comment]
>  I see aiormq just directly create_task with basic_qos

Can you pls link a code snippet of that? I looked at aiormq and found they have blocking frame handlers ([here](https://github.com/mosquito/aiormq/blob/eb1ebe5d1381f551a10cb99d07a95395e59c7cc3/aiormq/connection.py#L652))

**Comment by garvenlee** [comment]
Sorry, I may have made a mistake. What can really cause blocking should be the callbacks passed in by the user, such as `on_publish_confirm` and `subscribe_callback`, so such callbacks should be wrapped as `asyncio.Task`. Maybe here [aiormq](https://github.com/mosquito/aiormq/blob/eb1ebe5d1381f551a10cb99d07a95395e59c7cc3/aiormq/channel.py#L285)

**Comment by garvenlee** [comment]
In Python, StreamReaderProtocol uses this [Transport](https://github.com/python/cpython/blob/f2eaa92b0cc5a37a9e6010c7c6f5ad1a230ea49b/Lib/asyncio/selector_events.py#L1003), which reads up to 256kb from the underlying socket and feeds it into StreamReader’s buffer [(here)](https://github.com/python/cpython/blob/f2eaa92b0cc5a37a9e6010c7c6f5ad1a230ea49b/Lib/asyncio/streams.py#L273). So if it’s necessary to customize the data chunk processing, you need to rewrite `StreamReaderProtocol.data_received`. Then use the new StreamReaderProtocol to build connection, like [this](https://github.com/python/cpython/blob/f2eaa92b0cc5a37a9e6010c7c6f5ad1a230ea49b/Lib/asyncio/streams.py#L98).

> we should have more or less the same behaviour

I found that rstream's write-out rate can reach 1.4Mb/s, but the read rate is only 400kb/s, which I think has to do with the `Credit` of the protocol. So it’s necessary to optimize the read process of each connection.

**Comment by DanielePalaia** [comment]
Going back to the previous solution. If we just have a new single task that execute all the handlers?
We can have an asyncio.Queue to do the synchronization (even tough we still have to see about performance implications)
Something like this: https://github.com/qweeze/rstream/compare/improve_callback_handlers

I saw that with this we are already able to solve issue (as timetout) like: https://github.com/qweeze/rstream/issues/123

**Comment by garvenlee** [comment]
Use Queue means taking frames from the protocol's cache and putting them into another cache. Then deliver them to an asynchronous task, but actually `asyncio.Task`s can't be parallel, so this queue just introduce additional communication.

**Comment by DanielePalaia** [comment]
Well I'm noticing that the timeout is not anymore present simply with the modification as above (using the separate task with Queue), while is with the other approach so I think this is anyway an improvement.

**Comment by garvenlee** [comment]
I have a look at #123. I think the reason for `TimeoutError` is that consumer_handler waits the `sync_request`’s response, which blocks the `_listener`. So though the response frame already reached, but `_listener` can’t dispatch its handler.

This is similar to what I mentioned earlier.

> What can really cause blocking should be the callbacks passed in by the user, such as on_publish_confirm and subscribe_callback, so such callbacks should be wrapped as asyncio.Task.

**Comment by DanielePalaia** [comment]
Yes I can see that even with the separate task with queue if the user provide a long-running callback it is still blocking the listener.

Yes we can try to run on_publish_confirm and subscribe_callback as asyncio task but we need to be sure that the ordering of the messages get preserved.

**Comment by DanielePalaia** [comment]
@garvenlee I made a few tests and the fact is that even if we set the subscribe_callback to run as an asyncio.create_task if this callback is very intensive it will anyway keep all the context for itself. At minimum it needs to run an await asyncio.sleep(0) in order to release the context and give the other callbacks the possibility to be run.

**Comment by garvenlee** [comment]
As I know, if the task itself is asynchronous, it will not block the event loop, but if the task is cpu-intensive, the event loop must wait for it to complete.

**Comment by Gsantomaggio** [comment]
> if the callback is cpu-intensive,

do you mean user side?

**Comment by garvenlee** [comment]
Yes, asyncio isn’t preemptive, so just leave it to the user code to handle

**Comment by Gsantomaggio** [comment]
I may be missing something, but  It is not the library's responsibility. If the user puts some intensive CPU operation by blocking the task thread, we can't do too much.  

In the .dot net client, there is one single task; it is up to the user to decide what to do.

It is enough to handle the full-rate chunks download from the library perspective then is up to the user.

**Comment by DanielePalaia** [comment]
@garvenlee For the original timeout issue I can see that the solution posted before  https://github.com/qweeze/rstream/compare/improve_callback_handlers should be able to handle it properly.
I tried the https://github.com/qweeze/rstream/issues/123 scenario and it is working.
I will probably do further performance analysis in the next days.

I'm also trying to implement your solution, is partially working but for example I'm having some issues running the example: https://github.com/qweeze/rstream/issues/123 which is still failing (but probably for another reason)
Would you mind to open a PR so that we can check it?

**Comment by garvenlee** [comment]
This seems to be the case, but there may be some mechanism to limit the number of tasks for consumer callbacks. If the callback is slow, the underlying read buffer will accumulate enough data, which triggers tcp back pressure later.

**Comment by garvenlee** [comment]
> partially working but for example I'm having some issues running the example: https://github.com/qweeze/rstream/issues/123 which is still failing

I think it should be ensured that `close` is only called once. And consumer callback should be like:

```Python
async def on_message(msg, ctx):
    if not already_called:
        already_called = True
        await consumer.close()
        # notify user code to begin it’s own cleanup process.
        closed_waiter.set_result(None)
```

This cleanup logic requires user control, and it’s actually unreasonable to call `consumer.close` in the consumer callback.

**Comment by DanielePalaia** [comment]
Yah I agree it's unreasonable to call consumer.close in the consumer callback, it was just to test the scenario and see if the timeout was happening again.

This is the branch I tested:: https://github.com/qweeze/rstream/compare/making_user_callbacks_asynchronous
but it is still not working. 

Anyway no point to write here pieces of code I have to test. This is your idea, It will be easier if you can implement it and you can please open a PR, we will review it! Thanks!

**Comment by garvenlee** [comment]
The branch [(making_user_callbacks_asynchronous)](https://github.com/qweeze/rstream/compare/making_user_callbacks_asynchronous) is fine. 

The problem now lies in the test code because `consumer.close` is called multiple times.

**Comment by DanielePalaia** [comment]
I made a few tests today.

It seems like performance degrade quite a bit with this solution:

For example consuming 5 millions of entries we pass from 70 seconds of master to 130 of the branch https://github.com/qweeze/rstream/compare/making_user_callbacks_asynchronous

We should maybe try to limit the number of tasks create but to see how.

I also tested the solution in https://github.com/qweeze/rstream/compare/improve_callback_handlers
Here after a few millions messages read the listener get blocked in  self._conn.read_frame()

**Comment by DanielePalaia** [comment]
I made a few tests also using a Semaphore to limit the number of tasks spawn but performance are not really good also with that.

Considering also that with this implementation the users will have to tune the optimal number of tasks based on the architecture is using, I think that we will finally go with the single task syncrhonized by Queue discussed before like: https://github.com/qweeze/rstream/pull/134

For the test done this should be enough to keep the listener free in case the callback will attempt to submit a sync call too, like close() is doing or others and it will be also more in line with our other clients.

Also performance seems in line with the original branch.
