### ISSUE TITLE
Redesign Frame’s encode/decode

### ISSUE THREAD

**Issue by garvenlee** [qweeze/rstream#133]
Currently, `encode_frame` & `decode_frame` cause heavy loops and recursive function calls, which is really slow in python. It's necessary to avoid recursive calls. Maybe `encode_frame` can be like this:
```Python
def encode_frame(frame: Frame):
    return encoder_table[frame.__class__](frame)

# For Publish Frame, we already know its fields, 
# so it’s unnecessary to use the normal `encode_field`, which causes many redundant conditional statement and recursive calls.
 
def encode_publish(frame: Publish):
    with BytesIO() as fp:
        fp_write = fp.write        
        
        fp.seek(9)
        fp_write(frame.publisher_id.to_bytes(length=1, byteorder="big", signed=True))
        
        messages = frame.messages     
        fp_write(len(messages).to_bytes(4, "big", signed=False))             
        for msg in messages:            
            fp_write(msg.publishing_id.to_bytes(length=8, byteorder="big", signed=True))
            
            data = msg.data
            fp_write(len(data).to_bytes(4, "big", signed=False))
            fp_write(data)
        
        fp.seek(0)
        length = fp.getbuffer().nbytes - 4
        fp_write(length.to_bytes(4, "big", signed=False))
        fp_write(frame.key.value.to_bytes(2, "big", signed=False))
        fp_write(frame.version.to_bytes(2, "big", signed=False))
        
        return fp.getvalue()
```

I did a test using the following code:

```Python
def test_encode():    
    messages = []
    for i in range(1_000_000):        
        messages.append(Message(publishing_id=i, data=bytes(f"hey, {i}", "ascii")))
    
    frame = Publish(publisher_id=1, messages=messages)    
    
    start = monotonic()
    # rstream.encoding.encode_frame(frame)     
    encode_publish(frame)    
    end = monotonic()
    print(end - start)
```

Using `test_encode`, the encoding time for 1 million messages is as follows:

1. rstream.encoding.encode_frame: 3.82065393999801
2. encode_publish: 0.6640957179770

In addition, I also tested the `FrameEncoder` in `rbfly`, and got the time:  0.132. It is fastest, because its implementation is not pure python. If `rstream` doesn’t consider using cython acceleration, it’s worth rewriting the code like `encode_publish`.

**Comment by garvenlee** [comment]
Frames are encoded and decoded faster, which means that there are more time slices for read or write the underlying bytes. 

Assuming that the speed of the `send` becomes faster, due to the [removal of _buffered_messages_lock](https://github.com/qweeze/rstream/issues/127), writing out a large number of messages may pause the underlying `StreamWriter`(fairly rare). And at the same time, `_buffered_messages` may accumulate many messages without `_buffered_messages_lock`, which will cause the next write operation to block again. But when python handles heavy network data forwarding with asyncio.StreamReaderProtocol in a single thread, it’s a question that whether the message accumulation is as serious as thought.

**Comment by Gsantomaggio** [comment]
>  Maybe encode_frame can be like this:

I think you are right.


FYI, we are evaluating cython acceleration with optional flag. At the moment we have other priorities but it is something on the list. 

Please feel free to propose a PR with that.

**Comment by Gsantomaggio** [comment]
A note about `rbfly ` The AMQP 1.0 codec is not compatible with the other clients ( at least when we tested it )
Client compatibility is the main point for us.

**Comment by wrobell** [comment]
> A note about `rbfly `: The `rbfly` AMQP 1.0 codec is not compatible with the other clients ( at least when we tested it ) Client compatibility is the main point for us.

@Gsantomaggio I remember you raising the issue, see discussion here: https://gitlab.com/wrobell/rbfly/-/issues/1. Please do not hesitate to raise an issue against RbFly with *appropriate* details (at the level your team requires from others).

**Comment by Gsantomaggio** [comment]
@wrobell thank you. At the moment we are a bit busy. We tried to add rfly here: https://github.com/Gsantomaggio/rabbitmq-stream-mixing and we had some compatibility problems. 
BTW You can send messages from one of any client java,net, stream and AMQP to see if `rfly` can consume the messages 

Thanks
