### ISSUE TITLE
stompjs client cant subscribe msg published by rstream?

### ISSUE THREAD

**Issue by xuqinghan** [qweeze/rstream#15]
Publishing messages and Consuming messages is ok. [https://github.com/qweeze/rstream/blob/master/README.md](https://github.com/qweeze/rstream/blob/master/README.md)
but when use stormjs to consume  "mystream" created by rsteam:

[https://github.com/stomp-js/stompjs](https://github.com/stomp-js/stompjs)
[https://github.com/rabbitmq/rabbitmq-server/issues/3508](https://github.com/rabbitmq/rabbitmq-server/issues/3508)

```
import { Client, Message } from '../assets/stomp.umd.min.js'

console.log("hello world stream")

const client = new Client({
    brokerURL: 'ws://127.0.0.1:15674/ws',
    connectHeaders: {
        login: 'guest',
        passcode: 'guest'
    },
    debug: function (str) {
        console.log(str);
    },
    reconnectDelay: 5000,
    heartbeatIncoming: 4000,
    heartbeatOutgoing: 4000,
})


client.onConnect = function (frame) {

    console.log('Connected');

    let callback = function (message) {
        const msg = message.body
        console.log('callback ', msg);
        message.ack()
    }

    var subscription = client.subscribe(
        "/amq/queue/mystream", //created via rstream demo                        error
        //"/amq/queue/s_test",  // created via http://127.0.0.1:15672/#/queues   OK
        callback,
        {
            'ack': 'client-individual',
            'durable': true,
            'auto-delete': false,
            'x-queue-type': 'stream',
            'prefetch-count': 10,
            'x-stream-offset': 'last'
        })
}

client.activate()
```

when create a stream and publish a message(without any header ) manually from web management [http://127.0.0.1:15672/#/queues](http://127.0.0.1:15672/#/queues),  it's ok.

but cant subscribe  "mystream" created by rsteam, 
rabbitMQ server raise error:

> rabbitmq-stream_1  | 2022-03-10 08:34:49.742812+00:00 [info] <0.691.0> osiris_writer:init/1: name: __mystream_1646894235949435900 last offset: 99 committed chunk id: 99 epoch: 4
> rabbitmq-stream_1  | 2022-03-10 08:35:44.302586+00:00 [warn] <0.784.0> AMQP 0-9-1 client call timeout was 70000 ms, is updated to a safe effective value of 130000 ms
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0> ** Generic server <0.800.0> terminating
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0> ** Last message in was {'$gen_cast',
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                            {queue_event,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                {resource,<<"/">>,queue,<<"mystream">>},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                {osiris_offset,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                    {resource,<<"/">>,queue,<<"mystream">>},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                    99}}}
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0> ** When Server state == {ch,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                          {conf,running,rabbit_framing_amqp_0_9_1,1,<0.796.0>,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                           <0.796.0>,<0.788.0>,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                           <<"172.24.0.1:52798 -> 172.24.0.2:15674">>,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                           undefined,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                           {user,<<"guest">>,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                            [administrator],
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                            [{rabbit_auth_backend_internal,none}]},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                           <<"/">>,<<>>,<0.793.0>,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                           [{<<"publisher_confirms">>,bool,true},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                            {<<"exchange_exchange_bindings">>,bool,true},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                            {<<"basic.nack">>,bool,true},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                            {<<"consumer_cancel_notify">>,bool,true},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                            {<<"connection.blocked">>,bool,true},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                            {<<"authentication_failure_close">>,bool,true}],
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                           none,10,134217728,1800000,#{},1000000000},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                          {lstate,<0.799.0>,false},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                          none,1,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                          {0,{[],[]}},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                          {state,#{},erlang},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                          #{<<"T_sub-0">> =>
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                             {{amqqueue,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                               {resource,<<"/">>,queue,<<"mystream">>},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                               true,false,none,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                               [{<<"x-queue-type">>,longstr,<<"stream">>}],
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                               <0.691.0>,[],[],[],undefined,undefined,[],[],
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                               live,0,[],<<"/">>,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                               #{user => <<"guest">>},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                               rabbit_stream_queue,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                               #{epoch => 4,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                 event_formatter =>
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                  {rabbit_stream_queue,format_osiris_event,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                   [{resource,<<"/">>,queue,<<"mystream">>}]},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                 leader_locator_strategy => <<"client-local">>,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                 leader_node => rabbit@e88fe41271a0,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                 leader_pid => <0.691.0>,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                 name => "__mystream_1646894235949435900",
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                 nodes => [rabbit@e88fe41271a0],
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                 reference =>
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                  {resource,<<"/">>,queue,<<"mystream">>},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                 replica_nodes => [],retention => []}},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                              {false,10,false,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                               [{<<"x-stream-offset">>,longstr,<<"last">>}]}}},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                          #{{resource,<<"/">>,queue,<<"mystream">>} =>
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                             {1,{<<"T_sub-0">>,nil,nil}}},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                          {state,fine,5000,#Ref<0.3039776074.1391984642.38321>},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                          false,1,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                          {rabbit_confirms,undefined,#{}},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                          [],[],none,flow,[],
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                          {rabbit_queue_type,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                           #{{resource,<<"/">>,queue,<<"mystream">>} =>
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                              {ctx,rabbit_stream_queue,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                               {resource,<<"/">>,queue,<<"mystream">>},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                               {stream_client,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                "__mystream_1646894235949435900",
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                {resource,<<"/">>,queue,<<"mystream">>},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                <0.691.0>,<0.691.0>,1,#{},256,false,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                #{<<"T_sub-0">> =>
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                   {stream,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                    {resource,<<"/">>,queue,<<"mystream">>},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                    10,10,98,98,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                    {osiris_log,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                     {cfg,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                      "/var/lib/rabbitmq/mnesia/rabbit@e88fe41271a0/stream/__mystream_1646894235949435900",
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                      "__mystream_1646894235949435900",
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                      500000000,256000,#{},[],
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                      {write_concurrency,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                       #Ref<0.3039776074.1392115715.36239>},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                      undefined,#Fun<osiris_writer.4.53124714>,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                      #Fun<osiris_log.4.129764537>},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                     {read,offset,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                      #Ref<0.3039776074.1392115713.41625>,0,99,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                      tcp,user_data},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                     undefined,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                     {file_descriptor,prim_file,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                      #{handle =>
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                         #Ref<0.3039776074.1392115726.36064>,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                        owner => <0.800.0>,r_ahead_size => 0,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                        r_buffer =>
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                         #Ref<0.3039776074.1392115715.36238>}},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                     undefined}}},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                                <<"<0.800.0>_-7OviwPAH2WKsKPp8s-d-Bw">>}}},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                           #{}},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                          #Ref<0.3039776074.1391984642.38317>,false}
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0> ** Reason for termination ==
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0> ** {function_clause,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>        [{rabbit_msg_record,decode,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>             [[{'v1_0.header',undefined,undefined,undefined,undefined,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                   undefined},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>               {'v1_0.properties',undefined,undefined,undefined,undefined,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                   undefined,undefined,undefined,undefined,undefined,undefined,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>                   undefined,undefined,undefined},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>               {'v1_0.amqp_value',{utf8,<<"hello: 99">>}}],
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>              {undefined,undefined,undefined,undefined}],
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>             [{file,"rabbit_msg_record.erl"},{line,62}]},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>         {rabbit_msg_record,init,1,[{file,"rabbit_msg_record.erl"},{line,54}]},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>         {rabbit_stream_queue,binary_to_msg,2,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>             [{file,"rabbit_stream_queue.erl"},{line,915}]},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>         {rabbit_stream_queue,'-stream_entries/4-lc$^0/1-0-',5,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>             [{file,"rabbit_stream_queue.erl"},{line,888}]},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>         {rabbit_stream_queue,stream_entries,4,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>             [{file,"rabbit_stream_queue.erl"},{line,892}]},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>         {rabbit_stream_queue,'-handle_event/2-fun-1-',5,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>             [{file,"rabbit_stream_queue.erl"},{line,401}]},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>         {maps,fold_1,3,[{file,"maps.erl"},{line,410}]},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>         {rabbit_stream_queue,handle_event,2,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0>             [{file,"rabbit_stream_queue.erl"},{line,399}]}]}
> rabbitmq-stream_1  | 2022-03-10 08:35:44.323451+00:00 [erro] <0.800.0> 
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>   crasher:
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>     initial call: rabbit_channel:init/1
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>     pid: <0.800.0>
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>     registered_name: []
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>     exception exit: {function_clause,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                         [{rabbit_msg_record,decode,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                              [[{'v1_0.header',undefined,undefined,undefined,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                                    undefined,undefined},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                                {'v1_0.properties',undefined,undefined,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                                    undefined,undefined,undefined,undefined,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                                    undefined,undefined,undefined,undefined,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                                    undefined,undefined,undefined},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                                {'v1_0.amqp_value',{utf8,<<"hello: 99">>}}],
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                               {undefined,undefined,undefined,undefined}],
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                              [{file,"rabbit_msg_record.erl"},{line,62}]},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                          {rabbit_msg_record,init,1,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                              [{file,"rabbit_msg_record.erl"},{line,54}]},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                          {rabbit_stream_queue,binary_to_msg,2,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                              [{file,"rabbit_stream_queue.erl"},{line,915}]},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                          {rabbit_stream_queue,'-stream_entries/4-lc$^0/1-0-',
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                              5,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                              [{file,"rabbit_stream_queue.erl"},{line,888}]},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                          {rabbit_stream_queue,stream_entries,4,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                              [{file,"rabbit_stream_queue.erl"},{line,892}]},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                          {rabbit_stream_queue,'-handle_event/2-fun-1-',5,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                              [{file,"rabbit_stream_queue.erl"},{line,401}]},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                          {maps,fold_1,3,[{file,"maps.erl"},{line,410}]},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                          {rabbit_stream_queue,handle_event,2,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                              [{file,"rabbit_stream_queue.erl"},{line,399}]}]}
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>       in function  gen_server2:terminate/3 (gen_server2.erl, line 1183)
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>     ancestors: [<0.798.0>,rabbit_direct_client_sup,rabbit_sup,<0.228.0>]
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>     message_queue_len: 0
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>     messages: []
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>     links: [<0.798.0>,<0.796.0>]
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>     dictionary: [{process_name,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                       {rabbit_channel,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                           {<<"172.24.0.1:52798 -> 172.24.0.2:15674">>,1}}},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                   {permission_cache_can_expire,false},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                   {rand_seed,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                       {#{jump => #Fun<rand.3.92093067>,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                          max => 288230376151711743,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                          next => #Fun<rand.5.92093067>,type => exsplus},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                        [53738507667940155|90401130320299917]}},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                   {permission_cache,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                       [{{resource,<<"/">>,queue,<<"mystream">>},#{},read}]},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                   {channel_operation_timeout,15000},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                   {guid,{{3974881984,4027046242,2888366716,3018292743},0}}]
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>     trap_exit: true
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>     status: running
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>     heap_size: 4185
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>     stack_size: 29
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>     reductions: 88547
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>   neighbours:
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>     neighbour:
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>       pid: <0.796.0>
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>       registered_name: []
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>       initial call: amqp_channel:init/1
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>       current_function: {gen_server,loop,7}
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>       ancestors: [<0.794.0>,<0.791.0>,<0.787.0>,<0.786.0>,amqp_sup,<0.530.0>]
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>       message_queue_len: 0
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>       links: [<0.794.0>,<0.800.0>,<0.784.0>]
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>       trap_exit: false
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>       status: waiting
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>       heap_size: 610
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>       stack_size: 12
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>       reductions: 410
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>       current_stacktrace: [{gen_server,loop,7,[{file,"gen_server.erl"},{line,443}]},
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                   {proc_lib,init_p_do_apply,3,
> rabbitmq-stream_1  | 2022-03-10 08:35:44.326067+00:00 [erro] <0.800.0>                             [{file,"proc_lib.erl"},{line,226}]}]
> 
>

**Comment by Gsantomaggio** [comment]
Thank you for reporting. We will check it.

**Comment by Gsantomaggio** [comment]
The main problem is the AMQP 1.0 --> AMQP 0.9.1 compatibility. 
The Proton AMQP 1.0 ( used by this client) uses the `AMQPValue` field to store the body.
This is not compatible with the AMQP 0.9.1.

The other AMQP 1.0 implementations for Go,NET and Java use the `ApplicationData`  

Atm this kind of problem happens only with the stream Python client when:

1. send a message to a stream queue
2. consume a message using an AMQP client.


See also https://github.com/rabbitmq/rabbitmq-stream-go-client/pull/129 
and
https://github.com/rabbitmq/rabbitmq-stream-go-client/issues/128

**Comment by xuqinghan** [comment]
> 
Thanks. 

1. which AMQP version used by rabbitmq web management [http://127.0.0.1:15672/#/queues](http://127.0.0.1:15672/#/queues)  creating queue( kind = stream) and publishing message ?   

2 is there any way support AMQP 0.9.1  via "dedicated binary protocol" described in 
stream plugin document ? [https://www.rabbitmq.com/stream.html](https://www.rabbitmq.com/stream.html)

> 
> [Overview](https://www.rabbitmq.com/stream.html#overview)
> Streams are a new persistent and replicated data structure in RabbitMQ 3.9 which models an append-only log with non-destructive consumer semantics. They can be used as a regular AMQP 0.9.1 queue or through a [dedicated binary protocol](https://github.com/rabbitmq/rabbitmq-server/blob/v3.9.x/deps/rabbitmq_stream/docs/PROTOCOL.adoc) plugin and associated client(s).

**Comment by Gsantomaggio** [comment]
Please read this [post](https://gist.github.com/Gsantomaggio/149b604113bf9d2e044a0f89531c101f) about Stream-Core vs Stream-Plugin. 

The problem here is [this](https://gist.github.com/Gsantomaggio/149b604113bf9d2e044a0f89531c101f#interoperabilty-1)

The Python client uses the `AMQPValue` to store the body information and it is not supported from 1.0 to 0.9.1. That is your case.

**Comment by Gsantomaggio** [comment]
It works using the https://github.com/Azure/azure-uamqp-python as codec instead of qpid. 
uamqp-python is perfect compatible with Java,Go,.NET and AMQP 0.9.1 clients. 

I am still looking on QPID to see if there is a workaround

**Comment by Gsantomaggio** [comment]
Will closed via https://github.com/qweeze/rstream/pull/18
