### ISSUE TITLE
OverflowError: int too big to convert

### ISSUE THREAD

**Issue by afutureboss** [qweeze/rstream#153]
**when publisher_id =128 throw exception** 
  File "/XXX/venv/lib/python3.10/site-packages/rstream/encoding.py", line 139, in encode_publish
    fp_write(frame.publisher_id.to_bytes(length=1, byteorder="big", signed=True))

**Comment by Gsantomaggio** [comment]
Thank you for reporting

yes, this `fp_write(frame.publisher_id.to_bytes(length=1, byteorder="big", signed=True))` should be `fp_write(frame.publisher_id.to_bytes(length=1, byteorder="big", signed=False))`

**Comment by Gsantomaggio** [comment]
@afutureboss  FYI:  #154

**Comment by Gsantomaggio** [comment]
@afutureboss https://github.com/qweeze/rstream/releases/tag/0.14.2 let us know!
