### ISSUE TITLE
Change the default AMQP parser

### ISSUE THREAD

**Issue by Gsantomaggio** [qweeze/rstream#16]
@qweeze is it ok with you to change QPID with   [Azure AMQP 1.0]( https://github.com/Azure/azure-uamqp-python)  ?

It will fix https://github.com/qweeze/rstream/issues/15 and will make this client compatible with the other stream/amqp clients

**Comment by qweeze** [comment]
I submitted a quick drop-in replacement #18, can you check if this resolves the issue?

**Comment by Gsantomaggio** [comment]
Done via https://github.com/qweeze/rstream/pull/18#issuecomment-1073224975 thank you
