### ISSUE TITLE
Future must be safely set_result 

### ISSUE THREAD

**Issue by garvenlee** [qweeze/rstream#161]
At [this line](https://github.com/qweeze/rstream/blob/0d40653948f83beb98ffd91d5f4eb51f393ab3fc/rstream/client.py#L248), it’s safe to add `if not fut.done()` check before `set_result`, in case of `InvalidStateError`, because fut may be already timeout.

**Comment by DanielePalaia** [comment]
HI @garvenlee agree! Would you like to open a PR about it? I see you are using/studying this client carefully and providing great feedbacks! Many thanks about it! It would be nice if you'd like to contribute on it so the community can benefit!

**Comment by DanielePalaia** [comment]
Hi @garvenlee 
Please have a look to the PR if you have time and approve it
