### ISSUE TITLE
pypi: username/password authentication deprecated

### ISSUE THREAD

**Issue by DanielePalaia** [qweeze/rstream#168]
HI @qweeze 

It seems like that we are not able anymore to publish on pypi using username and password:

https://github.com/qweeze/rstream/actions/runs/7542265250/job/20530684097

I don't remember if you also provided a secret in the repo as we don't have visibility on them.

Is it possible for you to add a token in a secret in the repo as you did for the username and password?

Thank you!

**Comment by qweeze** [comment]
Hi @DanielePalaia 
It seems that pypi has deprecated username+password auth, so I added our github actions workflow to [trusted publishers](https://docs.pypi.org/trusted-publishers/) 

Can you pls check if it works now and let me know? (As I understand password is no longer needed now)

<img width="727" alt="image" src="https://github.com/qweeze/rstream/assets/14069116/6973e0d7-9a7a-478f-92a9-ec3f7aef349f">

**Comment by DanielePalaia** [comment]
Hey @qweeze thanks,

Actually I had some difficulties in the past using the gh-action-pypi-publish action so I decided to simply create the steps manually with poetry like:

#          export PATH="/home/runner/.local/bin:$PATH"
#          poetry config repositories.test-pypi $REPO
#          poetry build
#          poetry publish --username=$USER --password=$PASS

The issue I'm having using the action is this one:
https://github.com/qweeze/rstream/actions/runs/7553281421/job/20563793784

I'm not sure if this is because we are using poetry and if some prerequisite is needed before we call the publishing action

**Comment by qweeze** [comment]
I think the build step is missing - `poetry build` should be called at some point, and it should write files to `dist` directory, which the previous error is about

**Comment by DanielePalaia** [comment]
It seems working now yes the poetry build got missed! Thanks @qweeze
