### ISSUE TITLE
Support for load balancers within docker - official workaround

### ISSUE THREAD

**Issue by wonesy** [qweeze/rstream#17]
Referencing this article: https://blog.rabbitmq.com/posts/2021/07/connecting-to-streams/

There's a section on load balancers which states:

```
Client Workaround With a Load Balancer
A client application can still always connect to the load balancer and end up connected to the appropriate node. How can it do it? Two steps:

- use the metadata command but ignore the information and always connect to the load balancer
- retry connecting until it gets connected to the appropriate node

You may wonder how to find out about the node once a connection is established? The “coordinates” of the node (hostname and port, or advertised_host and advertised_port if configured) are available in a stream protocol connection. So a client application can know to which node it is connected to.
```

The default codepath for publish, for example, queries the leader and then attempts to connect directly. This doesn't work in a load balancer environment.

I'm not sure what the appropriate way to handle this is, either a parameter in the `Producer` class or a new function `publish_to_load_balancer(...)`

**Comment by Gsantomaggio** [comment]
we need to implement https://github.com/qweeze/rstream/issues/10 to handle the load balancer. 
In the same way, we do in Java, Go and .NET

**Comment by Gsantomaggio** [comment]
@qweeze I would close this one in favour of #10. 

I would implement this feature in the same way we [already did](https://github.com/qweeze/rstream/issues/17#issuecomment-1073225247)

**Comment by Gsantomaggio** [comment]
Hi @wonesy,
Sorry, here there is a misunderstanding about terms. 

I meant to say that we have to use `advertised_host` and `advertised_port` not set them.


When you receive a connection, you get also these values:
![Screen Shot 2022-03-21 at 16 36 07](https://user-images.githubusercontent.com/386987/159296288-3daf8d8f-d4bc-43f6-b554-8f31dd09e65c.png)


In the case of Load-balancer configuration we need to do something like:
https://github.com/rabbitmq/rabbitmq-stream-dotnet-client#load-balancer 

So we need to add an Address Resolver:
```
var lbAddressResolver = new AddressResolver(new IPEndPoint(IPAddress.Parse("<<loadBalancerIP>>"), 5552));
```

So what we need to do is to match the `Stream-Metadata` with the connection, see:

https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/main/RabbitMQ.Stream.Client/RoutingClient.cs#L80-L93


From the documentation:

>Client Workaround With a Load Balancer
A client application can still always connect to the load balancer and end up connected to the appropriate node. How can it do it? Two steps:

>use the metadata command but ignore the information and always connect to the load balancer
retry connecting until it gets connected to the appropriate node
