### ISSUE TITLE
Fail to build on Mac M* series 

### ISSUE THREAD

**Issue by Gsantomaggio** [qweeze/rstream#183]
The library does not work on Mac M* 
It is related to https://github.com/Azure/azure-uamqp-python/issues/386

**Comment by TeoLefebvre** [comment]
Same issue for me, are you planning to stop using uampq as it will be deprecated in 2025?

**Comment by Gsantomaggio** [comment]
@TeoLefebvre, we are working on a parser. but atm I don't have an ETA.

**Comment by lukebakken** [comment]
We should consider using this code:

https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/servicebus/azure-servicebus/azure/servicebus/_pyamqp

**Comment by lukebakken** [comment]
Also, see this - https://github.com/Azure/azure-uamqp-python/issues/374

**Comment by DanielePalaia** [comment]
Hi @TeoLefebvre I worked on an integration on this branch: https://github.com/qweeze/rstream/pull/194

Do you have some time to do a few tests? Thanks
