### ISSUE TITLE
Add CI action for publishing to PyPI

### ISSUE THREAD

**Issue by qweeze** [qweeze/rstream#20]

**Comment by Gsantomaggio** [comment]
I usually publish when a new tag is created.  
So we need two actions:
 - test: when push
 - publish to PyPI when tag

does it make sense to you?

**Comment by qweeze** [comment]
Yes, that makes sense. But we probably need to keep version in pyproject.toml in sync with git tags.
Ideally I'd like to have an action for release that will do several things atomically to avoid human errors:
 - bump version in pyproject.toml (by running `poetry version`)
- add a git tag with that version
- publish to PyPI

**Comment by DanielePalaia** [comment]
I'll close this one for now. We have a basic pipeline at the moment to publish to PyPI we can think to improve it on a next step of the development but for now it does what we need.
