### ISSUE TITLE
Add documentation or scripts for test setup

### ISSUE THREAD

**Issue by wonesy** [qweeze/rstream#23]
I dug through the fixtures and CI to reverse engineer how it was run, but it would be useful to add a script to start all of this up, or some docker compose files.

README could be augmented with a quick testing section

**Comment by Gsantomaggio** [comment]
part https://github.com/qweeze/rstream/pull/106

**Comment by DanielePalaia** [comment]
I will close this one now, doc has been created as well as tests/examples
