### ISSUE TITLE
Add more corner case unit tests

### ISSUE THREAD

**Issue by DanielePalaia** [qweeze/rstream#77]
Can be done together with https://github.com/qweeze/rstream/issues/67

To check carefully (and unit test) corner case conditions and exceptions managements like (stream not present, callbacks passed to functions not present or not correct ecc ecc...)

**Comment by DanielePalaia** [comment]
I think we are in a good shape regarding tests as we have a total coverage of 93% currently:

(rstream-py3.9) dpalaia@dpalaiaYMD6R rstream % coverage report
Name                              Stmts   Miss  Cover
-----------------------------------------------------
rstream/__init__.py                  21      3    86%
rstream/amqp.py                      16      1    94%
rstream/client.py                   271     41    85%
rstream/compression.py              120      9    92%
rstream/connection.py                46      3    93%
rstream/constants.py                 53      0   100%
rstream/consumer.py                 156      7    96%
rstream/encoding.py                 128     17    87%
rstream/exceptions.py                46      0   100%
rstream/producer.py                 229     33    86%
rstream/schema.py                   393      7    98%
rstream/superstream.py               52      4    92%
rstream/superstream_consumer.py      89     12    87%
rstream/superstream_producer.py      66      6    91%
rstream/utils.py                     28      1    96%
tests/__init__.py                     0      0   100%
tests/conftest.py                   133      1    99%
tests/http_requests.py               14      0   100%
tests/test_amqp.py                   17      0   100%
tests/test_client.py                 72      0   100%
tests/test_consumer.py              227      4    98%
tests/test_encoding.py               13      0   100%
tests/test_producer.py              181      4    98%
tests/util.py                        44      4    91%
-----------------------------------------------------
TOTAL                              2415    157    93%

**Comment by Gsantomaggio** [comment]
Add unit tests for the connection close. see https://github.com/qweeze/rstream/pull/94

**Comment by DanielePalaia** [comment]
In particular I take this issue in order to fully tests scenarios for this PR:

https://github.com/qweeze/rstream/pull/131

**Comment by DanielePalaia** [comment]
Status after https://github.com/qweeze/rstream/pull/140

```
---------- coverage: platform darwin, python 3.11.5-final-0 ----------
Name                              Stmts   Miss  Cover
-----------------------------------------------------
rstream/__init__.py                  22      3    86%
rstream/amqp.py                      16      1    94%
rstream/client.py                   329     49    85%
rstream/compression.py              120      9    92%
rstream/connection.py                46      2    96%
rstream/constants.py                 53      0   100%
rstream/consumer.py                 171     12    93%
rstream/encoding.py                 121     17    86%
rstream/exceptions.py                46      0   100%
rstream/producer.py                 267     38    86%
rstream/schema.py                   406      7    98%
rstream/superstream.py               52      4    92%
rstream/superstream_consumer.py      93     11    88%
rstream/superstream_producer.py      72      6    92%
rstream/utils.py                     32      1    97%
-----------------------------------------------------
TOTAL                              1846    160    91%
```
